In [1]:
import numpy as np

## numpy ndarray 개요
- 넘파이의 기반 데이터 타입은 ndarray임.
- ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음.

In [2]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 type 형태 : ', array1.shape)

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 type 형태 :  (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print(f'array1: {array1.ndim}차원, array2:{array2.ndim}차원, array3:{array3.ndim}차원')

array1: 1차원, array2:2차원, array3:2차원


- array1과 array3은 각각 데이터 수가 같지만 차원이 array1은 1차원, array2는 2차원으로 다름

## ndarray의 데이터 타입
- ndarray 내의 데이터 값은 숫자 값, 문자열 값, 불 값 등이 모두 사용 가능
- 그러나 ndarray 내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능, 즉 한 개의 ndarray 객체에 int나 float가 함께 있을 수 없음

In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # array1은 ndarray이고 .dtype은 ndarray 내의 데이터 타입을 반환한다.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


- 만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함

In [5]:
list2 = [1,2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1,2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


- ndarray 내 데이터값의 타입 변경도 astype() 메서드를 이용해 할 수 있다.
- 메모리를 더 절약해야할 때 보통 이용됨

In [6]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


## ndarray를 편리하게 생성하기 - arrange, zeros, ones
- 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우 위 세 개의 함수 사용

1. arrage()
- 함수 이름에서 알 수 있듯이 파이썬 표준 함수인 range()와 유사한 기능을 함. 쉽게 생각하면 array를 range()로 표현

In [7]:
sequence_array = np.arange(10) # 시작값도 설정 가능 range() 함수와 유사
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


2. zeros()
- 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
3. ones()
- zeros() 함수와 유사하게 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환

+) 함수 인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움

In [8]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


## ndarray의 차원과 크기를 번경하는 reshape()
- reshape() 메서드는 ndarray를 특정 차우너 및 크기로 변환한다.

In [10]:
array1 = np.arange(10)
print('array1:', array1)

array2 = array1.reshape(2, 5)
print('array2:', array2)

array3 = array1.reshape(5, 2)
print('array3:', array3)

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
array4 = array1.reshape(4,3) # reshape() 함수는 지정된 사이즈로 변경이 불가능하면 오류를 발생시킨다.

ValueError: cannot reshape array of size 10 into shape (4,3)

- reshape() 함수는 -1을 인자로 하면 ndarray와 호환되는 새로운 shape로 변환해준다

In [14]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
array4 = array1.reshape(4, -1) # 이 또한 마찬가지

ValueError: cannot reshape array of size 10 into shape (4,newaxis)

- -1 인자는 reshape(-1, 1)와 같은 형태로 자주 사용된다.
- reshape(-1, 1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장한다.

In [16]:
# 3차원을 2차원으로, 1차원을 2차원으로 reshape(-1, 1)을 이용하여 변경
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

1. 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환

2. 슬라이싱 : 슬라이싱은 연속된 인덱스상의 ndarray를 추출하는 방식 ':' 기호 사용

3. 팬시 인덱싱 : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환

4. 불린 인덱싱 : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

### 단일 값 추출

In [17]:
# 단일 값 추출

array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2] # array1[2]는 더 이상 ndarray 자료가 아닌 ndarray 내의 데이터값이다.(int)
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


- 인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있다.

In [18]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


- 단일 인덱스를 이용해 ndarray 내의 데이터값도 간단히 수정 가능하다.

In [19]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


- 다차원 ndarray에서 단일 값 추출

In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row = 0, col=0) index :', array2d[0,0])
print('(row = 0, col=1) index :', array2d[0,1])
print('(row = 1, col=0) index :', array2d[1,0])
print('(row = 1, col=1) index :', array2d[1,1])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col=0) index : 1
(row = 0, col=1) index : 2
(row = 1, col=0) index : 4
(row = 1, col=1) index : 5


- ndarray는 원래는 axis 구분을 가짐.(raw = axis 0, col = axis = 1)

### 슬라이싱

- ':'기호를 이용해 연속한 데이터를 슬라이싱해서 추출할 수 있음
- 단일 데이터값 추출을 제외하고 **슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입임**

In [21]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


- 슬라이싱 기호인 ':' 사이의 시작, 종료 인덱스는 생락이 가능하다.

1. ':' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스인 0으로 간주

2. ':' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주

3. ':' 기호 앞/뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주

In [22]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 2차원 ndarray에서 슬라이싱

In [23]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3, 3)
print('array2d"\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])


array2d"
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [24]:
# 뒤에 있는 인덱스를 없애면 한단계 낮은 차원의 ndarray를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [26]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] =>', array3.tolist()) # (0,2), (1,2)

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] =>', array4.tolist()) # ((0,0),(0,1)),((1,0),(1,1))

array5 = array2d[[0,1]]
print('array2d[[0,1]] =>', array5.tolist()) # ((0,:),(1,:))

array2d[[0,1], 2] => [3, 6]
array2d[[0,1], 0:2] => [[1, 2], [4, 5]]
array2d[[0,1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식

ex)1차원 ndarray[1,2,3,4,5]에서 데이터값이 3보다 크거나 같은 데이터만 추출하고 싶을 때 불린 인덱싱을 사용

In [27]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [28]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [29]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [30]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


- 불린 인덱싱이 동작하는 단계

1. array1d > 5와 같이 ndarray의 필터링 조건을 [] 안에 기재

2. False값은 무시하고 True값에 해당하는 인덱스값만 저장

3. 저장된 인데스 데이터 세트로 ndarray 조회

### 행렬의 정렬 - sort()와 argsort()

- 행렬 정렬 : 넘파이의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식과 ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있는데 np.sort()의 경우 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환하고 ndarray.sort()는 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None이다.

In [31]:
org_array = np.array([3,1,9,5])
print('원본 행렬:', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [33]:
# 내림차순
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


- 행렬이 2차원 이상일 경우에 axis축 값 설정을 통해 로우 방향, 또는 칼럼 방향으로 정렬을 수행할 수 있음

In [34]:
array2d = np.array([[8,12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬된 행렬의 인덱스를 반환하기
: 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때 np.argsort()를 이용한다.
np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.

In [35]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [36]:
# 내림차순 일 때
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [37]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78,95,84,98,88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 :', sort_indices_asc)
print('성적 오름차순 정렬 시 name_array의 이름 출력 :', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 : [0 2 4 1 3]
성적 오름차순 정렬 시 name_array의 이름 출력 : ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


- 위와 같은 예시로 인하여 argsort가 많이 쓰인다.

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

- 행렬내적(행렬 곱) : 행렬 내적은 행렬 곱이며, 두 행렬 A와 B의 내적은 np.dot()을 이용해 계산이 가능하다. 그리고 두 행렬 A와 B의 내적은 왼쪽 행렬의 로우(행)와 오른쪽 행렬의 칼럼(열)의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값이다.

In [39]:
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])
dot_product = np.dot(A, B)
print('행렬내적 결과:\n', dot_product)

행렬내적 결과:
 [[ 58  64]
 [139 154]]


- 전치행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬, 넘파이의 transpose()를 이용해 전치 행렬 구함

In [40]:
A = np.array([[1,2],
              [3,4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
