# Scikit-learn
- 파이썬 기반의 머신러닝을 위한 가장 쉽고 효율적인 개발 라이브러리를 제공

## 붓꽃 품종 예측하기

- 붓꽃 데이터 세트는 꽃잎의 길이와 너비, 꽃받침의 길이와 너비 피처(feature)를 기반으로 꽃의 품종을 예측하기 위한 것

### 분류(Classification) - 지도학습(Supervised Learning)

- 분류(Classification)는 대표적인 지도학습(Supervised Learning) 방법의 하나이다.

- 지도학습은 학습을 위한 다양한 피처와 분류 결정값인 레이블(Label) 데이터로 모델을 학습한 뒤, 별도의 테스트 데이터 세트에서 미지의 레이블을 예측

In [1]:
from sklearn.datasets import load_iris # 붓꽃 데이터 세트 생성
from sklearn.tree import DecisionTreeClassifier # 결정 트리 알고리즘 
from sklearn.model_selection import train_test_split # 데이터 세트를 학습 데이터와 테스트 데이터로 분리

# +)하이퍼 파라미퍼란? - 머신러닝 알고리즘별로 최적의 학습을 위해 직접 입력하는 파라미터들을 통칭하며, 하이퍼 파라미터를 통해 머신러닝 알고리즘의 성능을 튜닝할 수 있음.

In [2]:
import pandas as pd

# 붓꽃 데이터 세트 로딩
iris = load_iris()

# iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있음
iris_data = iris.data

# iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있음
iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

# 붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0


In [3]:
# train_test_split()을 이용하면 학습 데이터와 테스트 데이터를 test_size 파라미터 입력값의 비율로 쉽게 분할
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size=0.2, random_state=11)


- trin_test_split()의 첫 번째 파라미터인 iris_data는 피처 데이터 세트

- trin_test_split()의 두 번째 파라미터인 iris_label은 레이블(Label) 데이터 세트

- trin_test_split()의 세 번째 파라미터인 test_size는 전체 데이터 세트 중 테스트 데이터 세트의 비율

- trin_test_split()의 마지막 파라미터인 random_state는 호출할 때마다 같은 학습/테스트 용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값

- 참고) train_test_split()는 호출 시 무작위로 데이터를 분리함

In [4]:
# DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [5]:
# 학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

In [6]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9333


### 프로세스 정리

1. 데이터 세트 분리: 데이터를 학습 데이터와 테스트 데이터로 분리

2. 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습

3. 예측 수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류를 예측

4. 평가: 이렇게 예측된 결괏값과 테스트 데이터의 실제 결괏값을 비교해 ML 모델 성능을 평가


## 사이킷런의 기반 프레임워크 익히기

### Estimator 이해 및 fit(), predict() 메서드

- ML 모델 학습을 위해서 fit()을, 학습된 모델의 예측을 위해 predict() 메서드를 제공

- 지도학습의 주요 두 축인 분류(Classification)와 회귀(Regression)의 다양한 알고리즘을 구현한 모든 사이킷런 클래스는 fit()과 predict()만을 이용해 간단하게 학습과 예측 결과 반환

- 사이킷런에서는 분류 알고리즘을 구현한 클래스를 Classifier로, 그리고 회귀 알고리즘을 구현한 클래스를 Regressor로 지칭

- 이들 Classifier와 Regressor를 합쳐서 Estimator 클래스라고 부름. 즉, 지도학습의 모든 알고리즘을 구현한 클래스를 통칭해서 Estimator라고 부름

- croos_val_score()와 같은 evaluation 함수, GridSearchCV와 같은 하이퍼 파라미터 튜닝을 지원하는 클래스의 경우 이 Estimator를 인자로 받음

- 사이킷런에서 비지도학습인 차원 축소, 클러스터링, 피처 추출 등을 구현한 클래스 역시 대부분 fit()과 transform()을 적용함

- 비지도학습과 피처 추출에서 fit()은 입력 데이터의 형태에 맞춰 데이터를 변환하기 위한 사전 구조를 맞추는 작업임

- fit()으로 변환을 위한 사전 구조를 맞추면 이후 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 실제 작업은 transform()으로 수행

### 사이킷런의 주요 모듈
<table>
    <tr>
        <th>분류</th>
        <th>모듈명</th>
        <th>설명</th>
    </tr>
    <tr>
        <td>예제 데이터</td>
        <td>sklearn.datasets</td>
        <td>사이킷런에 내장되어 예제로 가공하는 데이터 세트</td>
    </tr>
    <tr>
        <td rowspan="3">피처 처리</td>
        <td>sklearn.preprocessing</td>
        <td>데이터 전처리에 필요한 다양한 가공 기능 제공(문자열을 숫자형 코드 값으로 인코딩, 정규화, 스케일링 등)</td>
    </tr>
    <tr>
        <td>sklearn.feature_selection</td>
        <td>알고리즘에 큰 영향을 미치는 피처를 우선순위대로 셀렉션 작업을 수행하는 다양한 기능 제공</td>
    </tr>
    <tr>
        <td>sklearn.feature_extraction</td>
        <td>텍스트 데이터나 이미지 데이터의 벡터화된 피처를 추출하는 데 사용됨</td>
    </tr>
    <tr>
        <td>피처 처리 & 차원 축소</td>
        <td>sklearn.decomposition</td>
        <td>차원 축소와 관련한 알고리즘을 지원하는 모듈임</td>
    </tr>
    <tr>
        <td>데이터 분리, 검증 & 파라미터 튜닝</td>
        <td>sklearn.model_selection</td>
        <td>교차 검증을 위한 학습용/테스트용 분리, 그리도 서치로 최적 파라미터 추출 등의 API 제공
    </tr>
    <tr>
        <td>평가</td>
        <td>sklearn.metrics</td>
        <td>분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공</td>
    </tr>
    <tr>
        <td rowspan="7">ML 알고리즘</td>
        <td>sklearn.ensemble</td>
        <td>앙상블 알고리즘 제공<br>
            랜덤 포레스트, 에이다 부스트, 그래디언트 부스팅 등 제공</td>
    </tr>
    <tr>
        <td>sklearn.linear_model</td>
        <td>주로 선형 회귀, 릿지(Ridge), 라쏘(Lasso) 및 로지스틱 회귀 등 회귀 관련 알고리즘을 지원, 또한 SGD 관련 알고리즘도 제공</td>
    </tr>
    <tr>
        <td>sklearn.naive_bayes</td>
        <td>나이브 베이즈 알고리즘 제공, 가우시안 NB, 다항 분포 NB 등</td>
    </tr>
    <tr>
        <td>sklearn.neighbors</td>
        <td>최근접 이웃 알고리즘 제공, K-NN 등</td>
    </tr>
    <tr>
        <td>sklearn.svm</td>
        <td>서포트 벡터 머신 알고리즘 제공</td>
    </tr>
    <tr>
        <td>sklearn.tree</td>
        <td>의사 결정 트리 알고리즘 제공</td>
    </tr>
    <tr>
        <td>sklearn.cluster</td>
        <td>비지도 클러스터링 알고리즘 제공(k-평균, 계층형, DBSCAN 등)</td>
    </tr>
    <tr>
        <td>유틸리티</td>
        <td>sklearn.pipeline</td>
        <td>피처 처리 등의 변환과 ML 알고리즘 학습, 예측 등을 함께 묶어서 실행할 수 있는 유틸리티 제공</td>
    </tr>
    
</table>

### 내장된 예제 데이터 세트

<table>
    <tr>
        <th>API명</th>
        <th>설명</th>
    </tr>
    <tr>
        <td>datasets.load_boston()</td>
        <td>회귀 용도이며, 미국 보스턴의 집 피처들과 가격에 대한 데이터 세트</td>
    </tr>
    <tr>
        <td>datasets.load_breast_cancer()</td>
        <td>분료 용도이며, 위스콘신 유방암 피처들과 악성/음성 레이블 데이터 세트</td>
    </tr>
    <tr>
        <td>datasets.load_diabetes()</td>
        <td>회귀 용도이며, 당뇨 데이터 세트</td>
    </tr>
    <tr>
        <td>datasets.load_digits()</td>
        <td>분류 용도이며, 0에서 9까지 숫자의 이미지 픽셀 데이터 세트</td>
    </tr>
    <tr>
        <td>datasets.load_iris()</td>
        <td>분류 용도이며, 붓꽃에 대한 피처를 가진 데이터 세트</td>
    </tr>
</table>

#### fetch 계열의 명령

- fetch_covtype() : 회귀 분석용 토지 조사 자료
- fetch_20newsgroups() : 뉴스 그룹 텍스트 자료
- fetch_olivetti_faces() : 얼굴 이미지 자료
- fetch_lfw_people() : 얼굴 이미지 자료
- fetch_rcv1() : 로이터 뉴스 말뭉치
- fetch_mldata() : ML 웹사이트에서 다운로드

- 표본 데이터 생성기

<table>
    <tr>
        <th>API명</th>
        <th>설명</th>
    </tr>
    <tr>
        <td>datasets.make_classifications()</td>
        <td>분류를 위한 데이터 세트를 만듬, 특히 높은 상관도, 불필요한 속성 등의 노이즈 효과를 위한 데이터를 무작위로 생성해줌.</td>
    </tr>
    <tr>
        <td>datasets.make_blobs()</td>
        <td>클러스터링을 위한 데이터 세트를 무작위로 생성, 군집 지정 개수에 따라 여러 가지 클러스터링을 위한 데이터 세트를 쉽게 만들어줌.</td>
    </tr>
    
</table>

- 키는 보통 data, target, target_name, feature_names, DESCR로 구성
    - data는 피처의 데이터 세트를 가리킴 -> ndarray type
    - target은 분류 시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트임 -> ndarray type
    - target_names는 개별 레이블의 이름을 나타냄 -> ndarray or list type
    - feature_names는 피처의 이름을 나타냄 -> ndarray or list type
    - DESCR은 데이터 세트에 대한 설명과 각 피처의 설명을 나타냄 -> string type

In [ ]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))
# Bunch 클래스는 파이썬 딕셔너리 자료형과 유사 

<class 'sklearn.utils._bunch.Bunch'>


In [2]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [5]:
print('\n feature_names 의 type:', type(iris_data.feature_names))
print(' feature_names 의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type:', type(iris_data.target_names))
print(' target_names의 shape:', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data 의 type:', type(iris_data.data))
print(' data 의 shape:', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type:', type(iris_data.target))
print(' target의 shape:', iris_data.target.shape)
print(iris_data.target)



 feature_names 의 type: <class 'list'>
 feature_names 의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type: <class 'numpy.ndarray'>
 target_names의 shape: 3
['setosa' 'versicolor' 'virginica']

 data 의 type: <class 'numpy.ndarray'>
 data 의 shape: (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]